version: "3.9"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    command: ["etcd", "-advertise-client-urls", "http://0.0.0.0:2379", "-listen-client-urls", "http://0.0.0.0:2379", "-listen-peer-urls", "http://0.0.0.0:2380", "-initial-advertise-peer-urls", "http://0.0.0.0:2380", "-initial-cluster", "default=http://0.0.0.0:2380", "-data-dir", "/var/lib/etcd"]
    volumes:
      - milvus-etcd:/var/lib/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    container_name: milvus-minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: ["minio", "server", "/data"]
    volumes:
      - milvus-minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5

  milvus:
    image: milvusdb/milvus:v2.4.3
    container_name: milvus-standalone
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MILVUS_LOG_LEVEL: info
    volumes:
      - milvus-data:/var/lib/milvus
    command: ["milvus", "run", "standalone"]

volumes:
  milvus-etcd:
  milvus-minio:
  milvus-data:
